spring.application.name=transactions_bot
server.port=${PORT:8080}
# MySQL database connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/Transactions

# MySQL database username
spring.datasource.username=root

# MySQL database password
spring.datasource.password=1504

spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

